### ISSUE TITLE
Error importing ONSPD data

### ISSUE THREAD

**Issue by Lana-chan** [DemocracyClub/uk-geo-utils#36]
### Issue and Steps to Reproduce
I have followed the installation and data import documentation, however I run into the following issue:

```
(.venv) synth@delta-flyer:~/aatp-insights$ python3 manage.py import_onspd --data-path .
Getting constraints and indexes for uk_geo_utils_onspd
Found primary key constraint
Found 0 foreign key constraints, where uk_geo_utils_onspd is the referencing or referenced table
Checking for non primary key/foreign key constraints...
...none found. Continuing.
Creating temp table called uk_geo_utils_onspd_temp...
importing from files..
checking header of ./ONSPD_AUG_2024_UK.csv
✓ Headers match
Importing ./ONSPD_AUG_2024_UK.csv
Dropping temp table if exists...
Traceback (most recent call last):
  File "/home/synth/aatp-insights/manage.py", line 22, in <module>
    main()
  File "/home/synth/aatp-insights/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/management/commands/import_onspd.py", line 109, in handle
    super().handle(**options)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/base_importer.py", line 336, in handle
    self.import_data_to_temp_table()
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/management/commands/import_onspd.py", line 26, in import_data_to_temp_table
    self.import_onspd(self.temp_table_name)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/management/commands/import_onspd.py", line 84, in import_onspd
    self.cursor.copy_expert(
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 31, in __getattr__
    cursor_attr = getattr(self.cursor, attr)
AttributeError: 'Cursor' object has no attribute 'copy_expert'
```

I believe the issue is due to the fact that Django now recommends psycopg version 3 rather than psycopg2. Removing the psycopg package and letting Django use uk_geo_utils' dependency psycopg2-binary results in the following:

```
(.venv) synth@delta-flyer:~/aatp-insights$ python3 manage.py import_onspd --data-path .
Getting constraints and indexes for uk_geo_utils_onspd
Found primary key constraint
Found 0 foreign key constraints, where uk_geo_utils_onspd is the referencing or referenced table
Checking for non primary key/foreign key constraints...
...none found. Continuing.
Creating temp table called uk_geo_utils_onspd_temp...
importing from files..
checking header of ./ONSPD_AUG_2024_UK.csv
✓ Headers match
Importing ./ONSPD_AUG_2024_UK.csv
Dropping temp table if exists...
Traceback (most recent call last):
  File "/home/synth/aatp-insights/manage.py", line 22, in <module>
    main()
  File "/home/synth/aatp-insights/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/management/commands/import_onspd.py", line 109, in handle
    super().handle(**options)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/base_importer.py", line 336, in handle
    self.import_data_to_temp_table()
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/management/commands/import_onspd.py", line 26, in import_data_to_temp_table
    self.import_onspd(self.temp_table_name)
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/uk_geo_utils/management/commands/import_onspd.py", line 84, in import_onspd
    self.cursor.copy_expert(
  File "/home/synth/aatp-insights/.venv/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 607, in copy_expert
    return self.cursor.copy_expert(sql, file, *args)
psycopg2.errors.SyntaxError: header requires a Boolean value
```

### Additional Details
Python 3.10.12
Django 5.1.3
uk_geo_utils 0.16.0
psycopg2-binary 2.9.10
ONSPD data: August 2024 https://ons.maps.arcgis.com/home/item.html?id=265778cd85754b7e97f404a1c63aea04

**Comment by GeoWill** [comment]
Hi @Lana-chan 
Thanks for the issue.

This way of importing the data is a bit new. I've only tried getting it to work on Django 4.2 and psycopg2. 

Saying that I just tried `pip install django==5.1.3` and the command to ran. 

So not reproducing locally for me - though I haven't tried anything else. 

Looking at the second stack trace it's falling over the value passed to `HEADER` in the copy statement. This code uses `MATCH` which is reasonably new and only introduced in postgresql 15. So if you're running an older postgresql version that could be an issue? 

### Versions 

This is just what I have locally. 

```shell
❯ psql --version
psql (PostgreSQL) 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)

❯ python
Python 3.12.7 (main, Oct 16 2024, 04:37:19) [Clang 18.1.8 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> import django
>>> psycopg2.__version__
'2.9.10 (dt dec pq3 ext lo64)'
>>> django.__version__
'5.1.3'
>>> 
```

**Comment by chris48s** [comment]
Couple of other quick things..

We do run the tests on django 5 and they pass
https://github.com/DemocracyClub/uk-geo-utils/blob/4fb6df1c74d9a3a4d24526065c77d166660caebe/.circleci/config.yml#L65

As a side note, I reckon we probably should drop the explicit requirement on `psycopg2-binary` in this lib, and let the host app install psycopg2, psycopg2-binary, psycopg3 as they see fit. I think although we are running raw SQL we don't actually explicitly interact with the postgres driver. It is all abstracted through django so I think the library itself should be able to be agnostic on this.

**Comment by Lana-chan** [comment]
> This code uses MATCH which is reasonably new and only introduced in postgresql 15. So if you're running an older postgresql version that could be an issue?

Aha, that was exactly it. Upgrading from 14 to 17 (we were on the distro's version, now on a custom apt source) fixed everything. Thank you!
